### ISSUE TITLE
Require error after upgrade to 0.1.15

### ISSUE THREAD

**Issue by mountaindude** [tverilytt/NODE-Red#5]
After upgrading to latest version 0.1.15 from some earlier version (not sure which) I get the warning below, which results in the node not loading in the Node-RED UI.

```
node-red-dev    | 3 Sep 07:50:34 - [warn] [node-red-contrib-yr/weather-info] Error: Cannot find module 'haversine-distance'
node-red-dev    | Require stack:
node-red-dev    | - /data/node_modules/node-red-contrib-yr/yr.js
node-red-dev    | - /data/node_modules/node-red-contrib-yr/weather-info/weather-info.js
node-red-dev    | - /usr/src/node-red/node_modules/@node-red/registry/lib/loader.js
node-red-dev    | - /usr/src/node-red/node_modules/@node-red/registry/lib/index.js
node-red-dev    | - /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
node-red-dev    | - /usr/src/node-red/node_modules/@node-red/runtime/lib/index.js
node-red-dev    | - /usr/src/node-red/node_modules/node-red/lib/red.js
node-red-dev    | - /usr/src/node-red/node_modules/node-red/red.js
```

Uninstalling > Re-installing the module solved the problem.

**Comment by hlovdal** [comment]
Same experience, only that I was unable to uninstall it from the UI.

On startup node-red complains

```text
Flows stopped due to missing node types.

    yr-config
    weather data
    weather info
```

and initial view in palette management shows that 3 nodes are in use

![screenshot 1](https://github.com/tverilytt/NODE-Red/assets/3678550/c87662eb-e7ea-49ad-bd10-72cdc1d49cb3)

But even after removing all visible references I could find (and restarting) there still is something that holds on to yr-config and prevents removal.

![screenshot 2](https://github.com/tverilytt/NODE-Red/assets/3678550/5adc686c-7cfd-4c32-8e41-d599bdbc033c)

"User settings > Event log" contains no details:

```text
-----------------------------------------------------------
2023-09-13T21:00:32.932Z Remove : node-red-contrib-yr


-----------------------------------------------------------
2023-09-13T21:00:44.665Z Remove : node-red-contrib-yr


-----------------------------------------------------------
2023-09-13T21:02:21.700Z Remove : node-red-contrib-yr


-----------------------------------------------------------
2023-09-13T21:03:06.985Z Remove : node-red-contrib-yr


-----------------------------------------------------------
2023-09-13T21:08:10.024Z Remove : node-red-contrib-yr

```

-------------

The remedy was to log in to the container and manually install the missing dependencies (in addition to `haversine-distance` there is an additional library used which is not (yet) listed as a dependency in `package.json`).

```bash
docker exec -ti node-red-node-red-1 bash
cd /data/node_modules/node-red-contrib-yr
npm install haversine-distance
npm install webidl-conversions
exit
docker compose down
docker compose up -d
```

After that the palette management status was a little bit different, but I was able to remove `
node-red-contrib-yr` successfully.
![screenshot 3](https://github.com/tverilytt/NODE-Red/assets/3678550/1686c8d0-5b31-4b08-a0f7-d08c47b341b9)

---------------

I reinstalled it and before doing anything else I manually installed the missing npm packages as described above and restarted. After that finally `node-red-contrib-yr` worked as expected.

**Comment by hlovdal** [comment]
Hm, short lived workaround. After installing some other nodes the installed packages were removed (I think I remember some message "X packages added, Y removed" or something like that, so possibly my installed packages were the removed ones). So I had to reinstall them manually again.

This makes `node-red-contrib-yr` rather unpleasant to use... Could you please merge my pull request @tverilytt ?

**Comment by tverilytt** [comment]
Thanks a bunch @mountaindude  and @hlovdal  for reporting on this, and @hlovdal  for the PR. I have merged and updated the version to 0.1.16 and pushed to npm. 

i had imported the "haversine-distance" module in my Node-RED projects, so did not realize it should be in the Yr package dependencies itself. :-/

I am not sure why I imported / required "webidl-conversions", maybe it is not needed. I will look into it :-)

It might take a little while before the 0.1.16 version is reflected in Node-RED node-red-contrib-yr repository, I will check back again tomorrow.

**Comment by hlovdal** [comment]
Thanks. Version 0.1.16 is current on npm, but https://flows.nodered.org/node/node-red-contrib-yr still reports 0.1.15 as latest, and as far as I understood the current situation is that there no longer is an automatic update from npm information and that [authors need to perform some manual update steps](https://discourse.nodered.org/t/how-to-add-update-nodes-to-the-flow-library/25294).

**Comment by tverilytt** [comment]
Thanks a lot, I was not aware of this new regime for updating on Node-RED site  😎
I have followed the instructions there now and then ran "check for update", and now the new version shows up.
