### PR TITLE
Add missing yr dependencies

### LINKED ISSUE #5: Require error after upgrade to 0.1.15
After upgrading to latest version 0.1.15 from some earlier version (not sure which) I get the warning below, which results in the node not loading in the Node-RED UI.

```
node-red-dev    | 3 Sep 07:50:34 - [warn] [node-red-contrib-yr/weather-info] Error: Cannot find module 'haversine-distance'
node-red-dev    | Require stack:
node-red-dev    | - /data/node_modules/node-red-contrib-yr/yr.js
node-red-dev    | - /data/node_modules/node-red-contrib-yr/weather-info/weather-info.js
node-red-dev    | - /usr/src/node-red/node_modules/@node-red/registry/lib/loader.js
node-red-dev    | - /usr/src/node-red/node_modules/@node-red/registry/lib/index.js
node-red-dev    | - /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
node-red-dev    | - /usr/src/node-red/node_modules/@node-red/runtime/lib/index.js
node-red-dev    | - /usr/src/node-red/node_modules/node-red/lib/red.js
node-red-dev    | - /usr/src/node-red/node_modules/node-red/red.js
```

Uninstalling > Re-installing the module solved the problem.

### PR DESCRIPTION
**Pull request by hlovdal**
This should fix issue #5.

### CODE REVIEW

**Comment by tverilytt** [comment]
Thanks a lot @hlovdal  :-)
